# Generated by Django 3.1.2 on 2020-10-25 07:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('minute', '0002_auto_20201024_1215'),
    ]

    operations = [
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(max_length=200)),
                ('rank', models.IntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='minutetopic',
            name='minute',
        ),
        migrations.AddField(
            model_name='meeting',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='meeting',
            name='secretary',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='meeting',
            name='start_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='topicconclusion',
            name='rank',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='topicdiscussion',
            name='rank',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='topictask',
            name='rank',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Minute',
        ),
        migrations.AddField(
            model_name='topic',
            name='meeting',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='minute.meeting'),
        ),
        migrations.AlterField(
            model_name='topicconclusion',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='minute.topic'),
        ),
        migrations.AlterField(
            model_name='topicdiscussion',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='minute.topic'),
        ),
        migrations.AlterField(
            model_name='topictask',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='minute.topic'),
        ),
        migrations.DeleteModel(
            name='MinuteTopic',
        ),
    ]
