# Generated by Django 3.1.2 on 2020-10-25 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('minute', '0005_auto_20201025_0842'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TopicTask',
        ),
    ]
