# Generated by Django 3.1.2 on 2020-11-01 15:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20201024_1215'),
        ('minute', '0006_delete_topictask'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.team'),
        ),
    ]
