# Generated by Django 3.1.2 on 2020-10-24 16:15

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('minute', '0002_auto_20201024_1215'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserTeam',
            new_name='TeamMember',
        ),
        migrations.RenameField(
            model_name='teammember',
            old_name='user',
            new_name='member',
        ),
    ]
