# Generated by Django 3.1.2 on 2020-11-02 14:57

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('account', '0002_auto_20201024_1215'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='teammember',
            unique_together={('team', 'member')},
        ),
    ]
